version: '3'
services:
    zap:
        build: zap
        ports:
            - 8090:8090
        command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    webgoat:
        image: webgoat/webgoat-8.0
        ports:
            - "8080:8080"
        volumes:
            - .:/home/webgoat/.webgoat
        working_dir: /home/webgoat
    seleniumbase:
        build: selenium_base_tests
        depends_on:
            - zap
            - webgoat
        command: pytest -s test_register_web_goat_SB.py --browser=chrome --headless

#        --proxy=zap:8090  seleniumbase.config.proxy_list.PROXY_LIST